name: Deploy with Poetry

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    env:
      PREFECT_CLOUD_API_KEY: ${{ secrets.PREFECT_CLOUD_API_KEY }}
      PREFECT_CLOUD_WORKSPACE: pawel-pozorski/default
      REPO_URL: https://github.com/Pawlo77/F1.git
      REPO_TOKEN: ${{ secrets.REPO_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.9'

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: 2.1.3

      - name: Cache virtualenv
        id: cache-venv
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry
            ~/.cache/pip
            .venv  # make sure you use `poetry config virtualenvs.in-project true`
          key: ${{ runner.os }}-venv-${{ hashFiles('F1/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-venv-

      - name: Install dependencies
        working-directory: F1
        run: |
          poetry config virtualenvs.in-project true
          poetry install --no-interaction

      - name: Deploy using Poetry
        working-directory: F1
        run: poetry run deploy
