name: Deploy with Poetry

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.9'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry
            ~/.cache/pip
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install dependencies
        working-directory: F1
        run: poetry install
      - name: Deploy using Poetry
        working-directory: F1
        run: poetry run deploy
        env:
          PREFECT_CLOUD_API_KEY: ${{ secrets.PREFECT_CLOUD_API_KEY }}
          PREFECT_CLOUD_WORKSPACE: pawel-pozorski/default
          REPO_URL_URL: https://github.com/Pawlo77/F1.git
          REPO_URL_TOKEN: ${{ secrets.REPO_URL_TOKEN }}
